#ifndef RALGO_HEIMER_SIGNAL_TYPES_H
#define RALGO_HEIMER_SIGNAL_TYPES_H

#define SIGNAL_TYPE_AXIS_STATE 1
#define SIGNAL_TYPE_SCALAR 2
#define SIGNAL_TYPE_DOF6 3

#define SIGNAL_TYPE_DATASIG_FLOAT 4
#define SIGNAL_TYPE_DATASIG_DOUBLE 5

#endif